Numpy is a Linear Algebra Library for Python

Numpy is very fast as it relies

Numpy arrays come in two falvors: vector and matrices

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [11]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Array Range

In [10]:
np.arange(0,10,2) 

array([0, 2, 4, 6, 8])

In [14]:
np.zeros((1,2))

array([[ 0.,  0.]])

In [15]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [18]:
np.linspace(1,5,10)

array([ 1.        ,  1.44444444,  1.88888889,  2.33333333,  2.77777778,
        3.22222222,  3.66666667,  4.11111111,  4.55555556,  5.        ])

### Identity matrix


In [21]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

### Random Array

In [23]:
np.random.rand(5)

array([ 0.02767859,  0.97686958,  0.72203402,  0.87718534,  0.69417409])

In [24]:
np.random.rand(5,5)

array([[ 0.81227796,  0.14305891,  0.91375317,  0.10170216,  0.3763543 ],
       [ 0.65132338,  0.84421409,  0.15681264,  0.19043347,  0.81993695],
       [ 0.53756261,  0.41188699,  0.06930861,  0.07925461,  0.04158026],
       [ 0.9233323 ,  0.78844972,  0.03135147,  0.14636928,  0.31891966],
       [ 0.66903115,  0.30235264,  0.1990484 ,  0.54853044,  0.30852894]])

### Normal Random distribution 

In [26]:
np.random.randn(5,5)

array([[ 0.98049396,  0.38613969, -0.54710098, -1.33984387, -0.11253877],
       [ 1.40448544, -0.22994124,  0.56160471,  1.14297819,  0.06591429],
       [-1.4619228 , -0.48261198,  0.15859354, -0.94533227, -0.35167818],
       [ 1.65904876,  1.37497731, -1.14476424,  1.54389723,  0.31094903],
       [-1.31164822,  1.31105976, -1.55601813,  1.88446257,  0.67729676]])

### Normal Random Integer

In [29]:
np.random.randint(1,100,5)

array([54, 16, 39,  3,  3])

In [49]:
arr = np.arange(25)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

### Reshape Array

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Max, Min and Index Location

In [34]:
arr.max()

24

In [35]:
arr.min()

0

In [39]:
arr.argmax() #index location of max

24

In [40]:
arr.argmin() #index location of min

0

### Shape

In [50]:
arr.shape

(25,)

In [51]:
arr=arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [54]:
arr.shape

(5, 5)

### Data type

In [53]:
arr.dtype

dtype('int32')

#### Alternative numpy call of random

In [55]:
from numpy.random import randint
randint(2,10)

8