In [3]:
import numpy as np
arr=np.arange(0,11)

In [4]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

### Broadcast

arr[0:5] = 100 #cast 100 into the first 5

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [16]:
arr=np.arange(0,11)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### slice of array

In [19]:
slice_of_arr = arr[0:6]

In [20]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [22]:
slice_of_arr[:] = 99

In [23]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [33]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### Copy of Array

In [34]:
arr_copy = arr.copy()   #makes a copy that you can modify and not affect original array (arr)

In [26]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [29]:
arr_copy[:]=100

In [30]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [31]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### n array

In [46]:
import numpy as np
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

*Double bracket notation*

In [47]:
print (arr_2d[0][0]) 
print (arr_2d[0][1])
print (arr_2d[0][2])
print (arr_2d[1][0]) 
print (arr_2d[1][1])
print (arr_2d[1][2])
print (arr_2d[2][0]) 
print (arr_2d[2][1])
print (arr_2d[2][2])


5
10
15
20
25
30
35
40
45


*Comma bracket notation*

In [48]:
print (arr_2d[0,0]) 

5


In [57]:
arr_2d[1:3,:]

array([[20, 25, 30],
       [35, 40, 45]])

In [58]:
arr_2d[1:3,:2]

array([[20, 25],
       [35, 40]])

### Conditional Select

In [59]:
arr = np.arange(1,11)

In [60]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
bool_arr = arr > 5

In [64]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [66]:
#or
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [67]:
arr[arr<3]

array([1, 2])

In [72]:
arr_2d = np.arange(50).reshape(5,10)

In [73]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [75]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])